/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Todo;

import java.awt.Desktop;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VINICIO
 */
public class Principal extends javax.swing.JFrame {

    private Usuarios ventanaUsuarios;
    private Proveedor ventanaProveedor;
    private Categoria ventanaCategoria;
    private Producto ventanaProducto;
    private IngresoProducto ventanaIngresoProducto;
    private Factura ventanaFactura;
    private boolean bandera = true;

    //private coneccion coneccion;
    public Principal() {
        int n;
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ventanaUsuarios = new Usuarios(btnClientes);
        ventanaProducto = new Producto(btnProducto);
        ventanaProveedor = new Proveedor(btnProveeedor);
        ventanaCategoria = new Categoria(btnCategoria);
        ventanaIngresoProducto = new IngresoProducto(btnIngreso);
        ventanaFactura = new Factura(btnFactura);
        escritorio.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        btnClientes = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnProveeedor = new javax.swing.JButton();
        btnIngreso = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto1.png"))); // NOI18N
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnProveeedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/provedor1.png"))); // NOI18N
        btnProveeedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveeedorActionPerformed(evt);
            }
        });

        btnIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pedidos.png"))); // NOI18N
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categoria1.png"))); // NOI18N
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        salir.setText("LOGIN");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        escritorio.setLayer(btnClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnProveeedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnFactura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(salir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClientes)
                    .addComponent(btnCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngreso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProveeedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnProducto)
                            .addComponent(btnClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProveeedor)
                        .addGap(18, 18, 18)))
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngreso)
                    .addComponent(btnFactura)
                    .addComponent(btnCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void finalize() throws Throwable {
        System.out.println("finalzado");
    }

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        if (ventanaUsuarios.isShowing() != true) {
            ventanaUsuarios = new Usuarios(btnClientes);
            btnClientes.setEnabled(false);
            escritorio.add(ventanaUsuarios);
            ventanaUsuarios.setVisible(true);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        if (ventanaProducto.isShowing() != true) {
            ventanaProducto = new Producto(btnProducto);
            btnProducto.setEnabled(false);
            escritorio.add(ventanaProducto);
            ventanaProducto.setVisible(true);
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnProveeedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveeedorActionPerformed
        if (ventanaProveedor.isShowing() != true) {
            ventanaProveedor = new Proveedor(btnProveeedor);
            btnProveeedor.setEnabled(false);
            escritorio.add(ventanaProveedor);
            ventanaProveedor.setVisible(true);
        }
    }//GEN-LAST:event_btnProveeedorActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        if (ventanaIngresoProducto.isShowing() != true) {
            ventanaIngresoProducto = new IngresoProducto(btnIngreso);
            ventanaIngresoProducto.setEnabled(false);
            escritorio.add(ventanaIngresoProducto);
            ventanaIngresoProducto.setVisible(true);
        }
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        if (ventanaFactura.isShowing() != true) {
            ventanaFactura = new Factura(btnFactura);
            btnFactura.setEnabled(false);
            escritorio.add(ventanaFactura);
            ventanaFactura.setVisible(true);
        }
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        if (ventanaCategoria.isShowing() != true) {
            ventanaCategoria = new Categoria(btnCategoria);
            btnCategoria.setEnabled(false);
            escritorio.add(ventanaCategoria);
            ventanaCategoria.setVisible(true);
        }
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Login vu = new Login();
        String[] args = null;
        vu.main(args);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveeedor;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
